### ISSUE TITLE
multithread analysis

### ISSUE THREAD

**Issue by hackoflpf** [REDasmOrg/REDasm#49]
hello,is there any settings that can enable the multithread analysis feature,when i analysis a file on windows platform,it just use one or 2 cpu core for analysis.

**Comment by Dax89** [comment]
The multithreaded analysis is already available.

I think you mean the parallelization in order to fetch and analyze more instructions at the same time which is not implemented, because it's tricky.
However you will not see all n-cores used at the same time because is the operating system that decides where to allocate those operations.
